# Generated by Django 2.2.6 on 2019-11-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_de_execucao', models.DateTimeField(auto_now=True, verbose_name='data de execução')),
                ('tipo_conta', models.CharField(max_length=200, verbose_name='tipo de conta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('status', models.BooleanField(default=False, verbose_name='paga')),
            ],
            options={
                'ordering': ['data_de_criacao'],
            },
        ),
    ]
